- name: apt-get update/upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=3600
- name: Ensure that common required packages are present
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
    - rsync
    - build-essential
    - git
