---
- name: apt-get update/upgrade
  apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: Ensure required packages are present
  apt: "name={{ item }} state=present"
  with_items: "{{ common_required_packages + common_extra_packages }}"
